version: '3.8'

services:
  weather:
    build: .
    environment:
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - DATABOX_TOKEN=${DATABOX_TOKEN}
    volumes:
      - ./logs:/app/logs
    command: ["php", "src/index.php", "weather"]

  github:
    build: .
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DATABOX_TOKEN=${DATABOX_TOKEN}
    volumes:
      - ./logs:/app/logs
    command: ["php", "src/index.php", "github"]

  tests:
    build: .
    environment:
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - DATABOX_TOKEN=${DATABOX_TOKEN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - .:/app
      - ./logs:/app/logs
    working_dir: /app
    command: ["./vendor/bin/phpunit", "--testdox", "tests/unit"]

  create-metrics:
    build: .
    environment:
      - DATABOX_TOKEN=${DATABOX_TOKEN}
    volumes:
      - .:/app
      - ./logs:/app/logs
    working_dir: /app
    command: ["php", "src/create_metrics.php"]
